import { asStableId, type JsonObject, type StableId } from '@haiyue/ai-studio-contracts';
import type { GameToolDefinition, GameToolEffect, GameToolRisk } from './types.js';

const empty = schema({}, []);
const entityId = Object.freeze({ type: 'string', pattern: '^entity:[A-Za-z0-9._:-]{3,120}$' });
const scriptId = Object.freeze({ type: 'string', pattern: '^script:[A-Za-z0-9._:-]{3,120}$' });
const componentId = Object.freeze({ type: 'string', pattern: '^component:[A-Za-z0-9._:-]{3,160}$' });
const componentType = Object.freeze({ type: 'string', pattern: '^[a-z][a-z0-9._:-]{2,159}$' });
const componentVersion = Object.freeze({ type: 'string', pattern: '^[0-9]+\\.[0-9]+\\.[0-9]+$' });
const componentValue = Object.freeze({ type: 'object', maxProperties: 256 });
const prefabId = Object.freeze({ type: 'string', pattern: '^prefab:[A-Za-z0-9._:-]{3,120}$' });
const scriptDigest = Object.freeze({ type: 'string', pattern: '^sha256:[a-f0-9]{64}$' });
const scriptPatchEdits = Object.freeze({ type: 'array', minItems: 1, maxItems: 64, items: Object.freeze({ type: 'object', additionalProperties: false, required: Object.freeze(['startLine', 'endLine', 'text']), properties: Object.freeze({ startLine: { type: 'integer', minimum: 1, maximum: 100_000 }, endLine: { type: 'integer', minimum: 1, maximum: 100_000 }, text: { type: 'string', maxLength: 32_768 } }) }) });
const revision = Object.freeze({ type: 'integer', minimum: 0 });
const sceneProjection = Object.freeze({ type: 'array', minItems: 1, maxItems: 7, uniqueItems: true, items: Object.freeze({ enum: ['hierarchy', 'components', 'scripts', 'assets', 'camera', 'render', 'settings'] }) });
const sceneScope = Object.freeze({
  type: 'object', additionalProperties: false, properties: Object.freeze({
    sceneId: { type: 'string', pattern: '^scene:[A-Za-z0-9._:-]{3,160}$' },
    entityIds: { type: 'array', maxItems: 1_000, uniqueItems: true, items: entityId },
    componentTypes: { type: 'array', maxItems: 128, uniqueItems: true, items: componentType },
  }),
});
const sceneCursor = Object.freeze({ type: 'string', minLength: 8, maxLength: 2_048 });
const sceneLimit = Object.freeze({ type: 'integer', minimum: 1, maximum: 1_000 });
const assetId = Object.freeze({ type: 'string', pattern: '^asset:[a-f0-9]{24}$' });
const assetKind = Object.freeze({ enum: ['texture', 'model', 'audio', 'animation'] });
const assetUsage = Object.freeze({ enum: ['texture.base-color', 'texture.metallic-roughness', 'texture.normal', 'texture.occlusion', 'texture.emissive', 'texture.environment-diffuse', 'texture.environment-specular', 'model', 'audio', 'animation'] });
const entityKind = Object.freeze({ enum: ['empty', 'cube', 'sphere', 'cone', 'cylinder', 'plane', 'torus', 'icosahedron', 'directional-light', 'point-light', 'ambient-light'] });
const geometryEntityKind = Object.freeze({ enum: ['cube', 'sphere', 'cone', 'cylinder', 'plane', 'torus', 'icosahedron'] });
const nonGeometryEntityKind = Object.freeze({ enum: ['empty', 'directional-light', 'point-light', 'ambient-light'] });
const materialKind = Object.freeze({ enum: ['basic', 'pbr', 'blinn-phong', 'normal'] });
const materialColor = Object.freeze({ type: 'array', minItems: 4, maxItems: 4, items: Object.freeze({ type: 'number', minimum: 0, maximum: 1 }) });
const vec3 = Object.freeze({ type: 'object', additionalProperties: false, required: Object.freeze(['x', 'y', 'z']), properties: Object.freeze({ x: { type: 'number' }, y: { type: 'number' }, z: { type: 'number' } }) });
const bounds3 = Object.freeze({ type: 'object', additionalProperties: false, required: Object.freeze(['minimum', 'maximum']), properties: Object.freeze({ minimum: vec3, maximum: vec3 }) });
const transform = Object.freeze({ type: 'object', additionalProperties: false, required: Object.freeze(['position', 'rotationDegrees', 'scale']), properties: Object.freeze({ position: vec3, rotationDegrees: vec3, scale: vec3 }) });
const entityCreateItem = Object.freeze({
  oneOf: Object.freeze([
    Object.freeze({ type: 'object', additionalProperties: false, required: Object.freeze(['kind']), properties: Object.freeze({ kind: geometryEntityKind, name: { type: 'string', minLength: 1, maxLength: 80 }, parentId: { anyOf: [entityId, { type: 'null' }] }, material: materialKind, color: materialColor, transform }) }),
    Object.freeze({ type: 'object', additionalProperties: false, required: Object.freeze(['kind']), properties: Object.freeze({ kind: nonGeometryEntityKind, name: { type: 'string', minLength: 1, maxLength: 80 }, parentId: { anyOf: [entityId, { type: 'null' }] }, transform }) }),
  ]),
});
const entityIds = Object.freeze({ type: 'array', minItems: 1, maxItems: 128, uniqueItems: true, items: entityId });
const transformAssignments = Object.freeze({
  type: 'array', minItems: 1, maxItems: 128,
  items: Object.freeze({ type: 'object', additionalProperties: false, required: Object.freeze(['entityId', 'transform']), properties: Object.freeze({ entityId, transform }) }),
});
const camera = Object.freeze({
  type: 'object', additionalProperties: false,
  required: Object.freeze(['projection', 'target', 'distance', 'azimuthDegrees', 'elevationDegrees', 'fovDegrees', 'orthographicSize', 'near', 'far']),
  properties: Object.freeze({
    projection: { enum: ['perspective', 'orthographic'] }, target: vec3,
    distance: { type: 'number', minimum: 0.5, maximum: 500 },
    azimuthDegrees: { type: 'number', minimum: -360, maximum: 360 },
    elevationDegrees: { type: 'number', minimum: -89.9, maximum: 90 },
    fovDegrees: { type: 'number', minimum: 10, maximum: 120 },
    orthographicSize: { type: 'number', minimum: 0.5, maximum: 500 },
    near: { type: 'number', minimum: 0.01, maximum: 100 },
    far: { type: 'number', minimum: 0.1, maximum: 10_000 },
  }),
});
const viewport = Object.freeze({ type: 'object', additionalProperties: false, required: Object.freeze(['x', 'y', 'width', 'height']), properties: Object.freeze({ x: { type: 'number', minimum: 0, maximum: 1 }, y: { type: 'number', minimum: 0, maximum: 1 }, width: { type: 'number', exclusiveMinimum: 0, maximum: 1 }, height: { type: 'number', exclusiveMinimum: 0, maximum: 1 } }) });
const targetSize = Object.freeze({ type: 'object', additionalProperties: false, required: Object.freeze(['width', 'height']), properties: Object.freeze({ width: { type: 'integer', minimum: 1, maximum: 16_384 }, height: { type: 'integer', minimum: 1, maximum: 16_384 } }) });
const resultSchema = Object.freeze({ type: 'object' }) as JsonObject;
const playInputEvent = Object.freeze({
  type: 'object', additionalProperties: false, required: Object.freeze(['tick', 'kind']), properties: Object.freeze({
    tick: { type: 'integer', minimum: 0, maximum: 1_000_000_000 },
    kind: { enum: ['action', 'pointer', 'reset'] }, source: { enum: ['synthetic', 'keyboard', 'pointer', 'gamepad', 'system'] },
    action: { type: 'string', minLength: 1, maxLength: 80 }, phase: { enum: ['down', 'value', 'up', 'move', 'cancel', 'wheel'] }, pointerId: { type: 'integer', minimum: 0, maximum: 1_000_000 },
    x: { type: 'number', minimum: 0, maximum: 1 }, y: { type: 'number', minimum: 0, maximum: 1 },
    button: { type: 'integer', minimum: -1, maximum: 31 }, wheelX: { type: 'number' }, wheelY: { type: 'number' }, value: { type: 'number' }, reason: { enum: ['blur', 'disconnect', 'stop', 'restart', 'cancel', 'manual'] },
  }),
});
const taskSpec = Object.freeze({ type: 'object', maxProperties: 8 });
const PARALLEL_SAFE_TOOL_IDS = new Set([
  'project.snapshot', 'scene.query', 'scene.diff', 'scene.get-many', 'tool.search', 'engine.capabilities.describe',
  'component.describe', 'component.get', 'camera.get', 'scene.list-entities',
  'entity.get', 'script.get', 'script.symbols', 'diagnostics.query', 'history.query', 'asset.search', 'asset.dependencies', 'task.evaluate',
]);

export const GAME_AUTHORING_TOOL_DEFINITIONS: readonly GameToolDefinition[] = Object.freeze([
  definition('project.snapshot', 'Project snapshot', 'Read the current project identity, revision and log health.', 'observe', 'low', empty, ['studio.project-workspace']),
  definition('scene.query', 'Query scene context', 'Read a paged immutable Scene projection at a retained revision. Scripts return metadata and digests, never source text. Use projection and scope to request only the exact hierarchy, components, scripts, assets, camera, render settings or project settings needed.', 'observe', 'low', schema({ revision, scope: sceneScope, projection: sceneProjection, cursor: sceneCursor, limit: sceneLimit }, [], ['revision', 'scope', 'projection', 'cursor', 'limit']), ['studio.project-workspace'], 10_000, 64 * 1024),
  definition('scene.diff', 'Diff scene revisions', 'Read a paged, provenance-carrying SceneDiffV1 between retained revisions. A stale cursor, future revision, revision gap or pruned history returns a recoverable diagnostic so the caller can request a new bounded scene.query baseline.', 'observe', 'low', schema({ fromRevision: revision, toRevision: revision, scope: sceneScope, projection: sceneProjection, cursor: sceneCursor, limit: sceneLimit }, ['fromRevision'], ['toRevision', 'scope', 'projection', 'cursor', 'limit']), ['studio.project-workspace'], 10_000, 64 * 1024),
  definition('scene.get-many', 'Get many entities', 'Read 1-128 exact entity snapshots in one bounded call, preserving request order and reporting missing ids. Components may be omitted when only hierarchy and transforms are needed.', 'observe', 'low', schema({ entityIds, includeComponents: { type: 'boolean' } }, ['entityIds'], ['includeComponents']), ['studio.project-workspace'], 10_000, 64 * 1024),
  definition('tool.search', 'Search authoring capabilities', 'Search the authoritative tool and component registries with local hybrid semantic matching. Results include provenance, capability groups, effects, risk and exact follow-up. Set includeSchemas only for the bounded matches that must be expanded next; the registry remains the schema owner.', 'observe', 'low', schema({ text: { type: 'string', minLength: 1, maxLength: 512 }, limit: { type: 'integer', minimum: 1, maximum: 50 }, includeSchemas: { type: 'boolean' } }, ['text'], ['limit', 'includeSchemas']), ['studio.component-registry'], 8_000, 64 * 1024),
  definition('engine.capabilities.describe', 'Describe engine capabilities', 'Read the frozen Component Registry capability manifest and its digest. Use this before adding gameplay components.', 'observe', 'low', empty, ['studio.component-registry']),
  definition('component.describe', 'Describe component', 'Read one versioned component schema, defaults, runtime adapter, effect and risk from the authoritative registry.', 'observe', 'low', schema({ type: componentType, version: componentVersion }, ['type'], ['version']), ['studio.component-registry']),
  definition('component.get', 'Get component', 'Read one component by id, or the first matching component on an entity by type and optional version.', 'observe', 'low', schema({ componentId, entityId, type: componentType, version: componentVersion }, [], ['componentId', 'entityId', 'type', 'version']), ['studio.project-workspace']),
  definition('camera.get', 'Get camera', 'Read the persisted main project camera used by both the authoring viewport and isolated game preview.', 'observe', 'low', empty, ['studio.project-workspace']),
  definition('scene.list-entities', 'List entities', 'Read a bounded immutable scene entity summary.', 'observe', 'low', empty, ['studio.scene-authoring']),
  definition('entity.get', 'Get entity', 'Read one immutable entity snapshot.', 'observe', 'low', schema({ entityId }, ['entityId']), ['studio.scene-authoring']),
  definition('script.get', 'Get script', 'Read one bounded project script snapshot.', 'observe', 'low', schema({ entityId, scriptId }, [], ['entityId', 'scriptId']), ['studio.script-preview']),
  definition('script.symbols', 'Read script symbols', 'Read a bounded structural index for one script: declared functions, variables, referenced api namespaces, input actions and observation ids. Source text is not returned.', 'observe', 'low', schema({ entityId, scriptId }, [], ['entityId', 'scriptId']), ['studio.script-preview'], 8_000, 32 * 1024),
  definition('diagnostics.query', 'Query diagnostics', 'Query bounded redacted Operation Log summaries.', 'observe', 'low', schema({
    severity: { type: 'array', maxItems: 4, uniqueItems: true, items: { enum: ['debug', 'info', 'warning', 'error'] } },
    kinds: { type: 'array', maxItems: 32, uniqueItems: true, items: { type: 'string', maxLength: 96 } },
    sessionId: { type: 'string' }, turnId: { type: 'string' }, toolCallId: { type: 'string' }, entityId: { type: 'string' }, pluginId: { type: 'string' },
    afterSequence: revision, beforeSequence: revision, limit: { type: 'integer', minimum: 1, maximum: 100 }, traverseCorrelation: { type: 'boolean' }, cursor: { type: 'string', maxLength: 2048 },
  }, ['limit', 'traverseCorrelation'], ['severity', 'kinds', 'sessionId', 'turnId', 'toolCallId', 'entityId', 'pluginId', 'afterSequence', 'beforeSequence', 'cursor']), ['studio.diagnostics.query'], 8_000, 64 * 1024),
  definition('history.query', 'Query document history', 'Read a bounded immutable projection of the shared Document History, including Undo/Redo availability and entry labels. Command payloads, script source and inverse operations are never exposed.', 'observe', 'low', schema({ beforeEntryId: { type: 'integer', minimum: 1 }, limit: { type: 'integer', minimum: 1, maximum: 100 } }, [], ['beforeEntryId', 'limit']), ['studio.project-workspace'], 8_000, 32 * 1024),
  definition('asset.search', 'Search project assets', 'Search the bounded controlled project asset catalog by text and kind.', 'observe', 'low', schema({ text: { type: 'string', maxLength: 256 }, kind: assetKind, limit: { type: 'integer', minimum: 1, maximum: 200 } }, [], ['text', 'kind', 'limit']), ['studio.project-workspace']),
  definition('asset.dependencies', 'Read asset dependencies', 'Read exact component references to controlled assets, optionally scoped to one asset or entity. Binary payloads and script source are never returned.', 'observe', 'low', schema({ assetId, entityId }, [], ['assetId', 'entityId']), ['studio.project-workspace'], 8_000, 32 * 1024),
  definition('camera.set', 'Set camera', 'Replace the persisted main project camera through Document History. Call camera.get first and submit a complete camera. elevationDegrees is the angle above the ground plane. orthographicSize is the full visible vertical span, not a half-size: fitting world width W and height H at viewport aspect A requires at least max(H, W/A), plus padding. Prefer camera.author frame-bounds when exact gameplay bounds are known.', 'reversible-edit', 'low', schema({ baseRevision: revision, camera }, ['baseRevision', 'camera'], []), ['studio.project-workspace']),
  definition('camera.author', 'Author gameplay camera', 'Create, activate, frame one entity, deterministically frame explicit world bounds, orbit, follow, change projection, or change viewport. frame-bounds computes an orthographic camera from minimum/maximum coordinates, plane, targetSize {width,height} and padding; Studio derives width/height itself so portrait previews cannot be inverted or clip the horizontal gameplay span. All changes are atomic and recoverable.', 'reversible-edit', 'medium', schema({ baseRevision: revision, action: { enum: ['create', 'activate', 'frame', 'frame-bounds', 'orbit', 'follow', 'projection', 'viewport'] }, entityId, targetEntityId: entityId, name: { type: 'string', minLength: 1, maxLength: 80 }, transform, projection: { enum: ['perspective', 'orthographic'] }, fovDegrees: { type: 'number', minimum: 1, maximum: 179 }, orthographicHeight: { type: 'number', minimum: 0.01, maximum: 10_000 }, near: { type: 'number', minimum: 0.0001, maximum: 1_000 }, far: { type: 'number', minimum: 0.001, maximum: 1_000_000 }, viewport, mode: { enum: ['position', 'look-at', 'position-and-look-at'] }, offset: vec3, lookAtOffset: vec3, smoothing: { type: 'number', minimum: 0, maximum: 1 }, padding: { type: 'number', minimum: 1, maximum: 100 }, bounds: bounds3, plane: { enum: ['xy', 'xz', 'yz'] }, targetSize, azimuthDelta: { type: 'number', minimum: -360, maximum: 360 }, elevationDelta: { type: 'number', minimum: -180, maximum: 180 }, distance: { type: 'number', minimum: 0.5, maximum: 500 } }, ['baseRevision', 'action'], ['entityId', 'targetEntityId', 'name', 'transform', 'projection', 'fovDegrees', 'orthographicHeight', 'near', 'far', 'viewport', 'mode', 'offset', 'lookAtOffset', 'smoothing', 'padding', 'bounds', 'plane', 'targetSize', 'azimuthDelta', 'elevationDelta', 'distance']), ['studio.project-workspace', 'studio.component-registry'], 15_000, 64 * 1024, true),
  definition('entity.create', 'Create entity', 'Create one low-risk authoring-scene entity after the implementation plan is approved, including its initial Transform and entity-specific material appearance in the same operation. When two or more independent entities are known, use entity.create-many instead. Use transform here instead of a dependent transform.set call for a new entity. Geometry kinds: cube, sphere, cone, cylinder, plane, torus, icosahedron. A plane is authored in local XY; rotate it -90 degrees around X when it must be a horizontal XZ floor viewed from above. Light kinds: directional-light, point-light and ambient-light. Empty is for logic/grouping. Only geometry kinds accept material/color; lights and empty must omit both. Geometry supports Engine material types basic, pbr, blinn-phong and normal plus an RGBA color with normalized 0..1 channels. Use basic for self-lit arcade/gameplay colors. PBR and blinn-phong require at least one Scene light (or environment light) before preview validation. Give visually distinct gameplay roles deliberate colors.', 'reversible-edit', 'low', schema({ baseRevision: revision, kind: entityKind, name: { type: 'string', minLength: 1, maxLength: 80 }, parentId: { anyOf: [entityId, { type: 'null' }] }, material: materialKind, color: materialColor, transform }, ['baseRevision', 'kind'], ['name', 'parentId', 'material', 'color', 'transform']), ['studio.scene-authoring']),
  definition('entity.create-many', 'Create scene entities', 'Create 1-32 already-known scene entities atomically in one document revision and one Undo/Redo entry. Prefer this over repeated entity.create calls. Every item includes its initial Transform; only geometry kinds accept material/color, while lights and empty must omit both. A plane is local XY and therefore needs rotationDegrees.x=-90 when used as a horizontal XZ floor. Use basic for self-lit arcade/gameplay colors; PBR and blinn-phong require a Scene or environment light. parentId may reference an entity that already exists before this operation.', 'reversible-edit', 'medium', schema({ baseRevision: revision, entities: { type: 'array', minItems: 1, maxItems: 32, items: entityCreateItem } }, ['baseRevision', 'entities'], []), ['studio.project-workspace', 'studio.scene-authoring'], 15_000, 64 * 1024, true),
  definition('entity.rename', 'Rename entity', 'Prepare and rename one entity through Document History.', 'reversible-edit', 'medium', schema({ baseRevision: revision, entityId, name: { type: 'string', minLength: 1, maxLength: 80 } }, ['baseRevision', 'entityId', 'name'], []), ['studio.scene-authoring'], 10_000, 32 * 1024, true),
  definition('entity.hierarchy', 'Edit entity hierarchy', 'Clone, reparent, or recoverably remove an entity subtree through one Document History transaction. Descendant expansion is explicit and bounded; removal always preserves Undo/Redo evidence.', 'reversible-edit', 'medium', schema({ baseRevision: revision, action: { enum: ['clone', 'reparent', 'delete'] }, entityId, parentId: { anyOf: [entityId, { type: 'null' }] }, name: { type: 'string', minLength: 1, maxLength: 80 }, order: { type: 'integer', minimum: 0, maximum: 1_000_000 }, includeDescendants: { type: 'boolean' } }, ['baseRevision', 'action', 'entityId'], ['parentId', 'name', 'order', 'includeDescendants']), ['studio.project-workspace'], 15_000, 64 * 1024, true),
  definition('prefab.manage', 'Capture or instantiate prefab', 'Capture one bounded entity subtree as a reusable project prefab, instantiate it with fresh entity/component/script ids, or recoverably remove it. Prefab mutations and instances use one shared Document History transaction; tool results never return captured script source.', 'reversible-edit', 'medium', schema({ baseRevision: revision, action: { enum: ['capture', 'instantiate', 'remove'] }, prefabId, entityId, parentId: { anyOf: [entityId, { type: 'null' }] }, name: { type: 'string', minLength: 1, maxLength: 80 } }, ['baseRevision', 'action', 'prefabId'], ['entityId', 'parentId', 'name']), ['studio.project-workspace', 'studio.component-registry'], 15_000, 64 * 1024, true),
  definition('transform.set', 'Set Transform', 'Replace the Transform of an existing entity. entityId is mandatory; when an entity was just created, wait for entity.create to return result.entity.id before calling this tool.', 'reversible-edit', 'medium', schema({ baseRevision: revision, entityId, transform }, ['baseRevision', 'entityId', 'transform'], []), ['studio.scene-authoring'], 10_000, 32 * 1024, true),
  definition('transform.batch', 'Batch spatial transform', 'Set, align, distribute, snap, or orient 1-128 entities in one revision and one Undo/Redo entry. This is the preferred spatial operation for boards, level layout, cameras, racers, platforms and spawn formations.', 'reversible-edit', 'medium', schema({ baseRevision: revision, action: { enum: ['set', 'align', 'distribute', 'snap', 'look-at'] }, entityIds, transforms: transformAssignments, axis: { enum: ['x', 'y', 'z'] }, mode: { enum: ['min', 'center', 'max'] }, spacing: { type: 'number' }, grid: { type: 'number', exclusiveMinimum: 0 }, target: vec3 }, ['baseRevision', 'action'], ['entityIds', 'transforms', 'axis', 'mode', 'spacing', 'grid', 'target']), ['studio.project-workspace'], 15_000, 64 * 1024, true),
  definition('material.set', 'Set material appearance', 'Create or replace the entity-specific material appearance of an existing geometry entity through Document History. Choose a built-in Engine material type and optionally an RGBA color with normalized 0..1 channels.', 'reversible-edit', 'medium', schema({ baseRevision: revision, entityId, material: materialKind, color: materialColor }, ['baseRevision', 'entityId', 'material'], ['color']), ['studio.scene-authoring'], 10_000, 32 * 1024, true),
  definition('component.add', 'Add component', 'Create a registry-validated component on an entity through the shared Document History path. Effect, risk, defaults and runtime ownership are derived from the registered component definition.', 'reversible-edit', 'high', schema({ baseRevision: revision, entityId, type: componentType, version: componentVersion, enabled: { type: 'boolean' }, value: componentValue }, ['baseRevision', 'entityId', 'type'], ['version', 'enabled', 'value']), ['studio.project-workspace', 'studio.component-registry'], 10_000, 64 * 1024, true),
  definition('component.set', 'Set component', 'Replace the complete value of an existing component through Document History after registry validation. Effect and risk are derived from the existing component definition.', 'reversible-edit', 'high', schema({ baseRevision: revision, componentId, enabled: { type: 'boolean' }, value: componentValue }, ['baseRevision', 'componentId', 'value'], ['enabled']), ['studio.project-workspace', 'studio.component-registry'], 10_000, 64 * 1024, true),
  definition('component.remove', 'Remove component', 'Remove one component through Document History. The exact target, effect and risk are derived from the current document and registry.', 'reversible-edit', 'high', schema({ baseRevision: revision, componentId }, ['baseRevision', 'componentId'], []), ['studio.project-workspace', 'studio.component-registry'], 10_000, 32 * 1024, true),
  definition('component.configure', 'Configure semantic component', 'Registry-driven upsert or recoverable removal using a partial value patch. Existing values are preserved; new components start from authoritative defaults. Use tool.search and component.describe instead of inventing fields.', 'reversible-edit', 'high', schema({ baseRevision: revision, action: { enum: ['upsert', 'remove'] }, entityId, type: componentType, version: componentVersion, enabled: { type: 'boolean' }, patch: componentValue }, ['baseRevision', 'action', 'entityId', 'type'], ['version', 'enabled', 'patch']), ['studio.project-workspace', 'studio.component-registry'], 12_000, 64 * 1024, true),
  definition('asset.import', 'Register project asset', 'Validate and register one file already contained under the project assets directory with explicit kind, format, decode budget, license and provenance. Texture imports must include width and height matching the file header; external model or animation URI fields are rejected.', 'reversible-edit', 'high', schema({ baseRevision: revision, projectPath: { type: 'string', minLength: 8, maxLength: 512 }, kind: assetKind, mimeType: { type: 'string', minLength: 3, maxLength: 128 }, license: { enum: ['project-owned', 'cc0', 'cc-by-4.0', 'internal-test'] }, provenance: { type: 'string', minLength: 1, maxLength: 512 }, decodedBytes: { type: 'integer', minimum: 1, maximum: 134217728 }, width: { type: 'integer', minimum: 1, maximum: 8192 }, height: { type: 'integer', minimum: 1, maximum: 8192 } }, ['baseRevision', 'projectPath', 'kind', 'mimeType', 'license', 'provenance', 'decodedBytes'], ['width', 'height']), ['studio.project-workspace'], 20_000, 32 * 1024, true, ['projectPath']),
  definition('asset.assign', 'Assign project asset', 'Assign a catalog asset to a compatible runtime component on one entity through the shared Document History path.', 'reversible-edit', 'high', schema({ baseRevision: revision, entityId, assetId, usage: assetUsage }, ['baseRevision', 'entityId', 'assetId', 'usage'], []), ['studio.project-workspace', 'studio.component-registry'], 10_000, 32 * 1024, true),
  definition('script.propose', 'Propose script', 'Validate a strict-TypeScript onUpdate function-body script and return a bounded diff proposal without committing. The text runs once per fixed Play tick with entity, component, world, time, delta and api already in scope; time and delta are milliseconds. Explicitly type every declared function, arrow-function and callback parameter: implicit any is rejected. component.data is the only persistent mutable ScriptComponent state across ticks; do not invent component.events or other ScriptComponent members. Do not use import, export, CommonJS, or a lifecycle-function wrapper. Input is only through api.input: wasPressed(action) is one tick, isPressed(action)/isDown(action) remain true while held, value(action) reads an axis, and pointerEvents() returns pointer-only events whose type is down/move/up/cancel/wheel and whose x/y are viewport-normalized 0..1 values. api.scene.instances(entityId, capacity) controls reusable dynamic instance data: capacity is immutable for a Play run and must be a numeric literal or const-only numeric expression; allocate a fixed maximum once, then call setCount(activeCount) and set(index, transform) as the active population changes. api.scene.hudText(id, text, options) creates or updates responsive Play HUD text; reuse the id each tick and removeHudText(id) when no longer needed. api.scene.observe(id, value) publishes bounded JSON gameplay state to play.inspect. Use stable observation ids and the generic schemaVersion 1 payload: state/status/phase, exact events/triggers lower-kebab-case transition names, space dimensions/bounds/axes, scalar metrics, stable-role actors and targets with grid/cell or world positions. normalized interactionTargets may additionally guide pointer input but do not replace authoritative positions. Remove observations when obsolete. api.physics exposes bounded body, collision/trigger event, grounded, force/impulse, velocity, raycast and overlap operations backed by configured Engine physics components. Studio infers scene and physics capabilities from source; reuse the returned capabilities for preview.validate.', 'trusted-code', 'high', schema({ baseRevision: revision, entityId, text: { type: 'string', minLength: 1, maxLength: 65536 }, capabilities: { type: 'array', maxItems: 6, uniqueItems: true, items: { enum: ['read', 'input', 'debug', 'scene', 'physics', 'asset'] } } }, ['baseRevision', 'entityId', 'text'], ['capabilities']), ['studio.script-preview'], 20_000, 64 * 1024, false, ['text']),
  definition('script.patch', 'Patch script lines', 'Apply non-overlapping line edits to an exact script digest and return the same validated proposal contract as script.propose. Identify the target with entityId, scriptId, or both; when both are supplied Studio verifies that they identify the same script. This reduces source retransmission while remaining stale-safe; it never commits directly.', 'trusted-code', 'high', schema({ baseRevision: revision, entityId, scriptId, expectedDigest: scriptDigest, edits: scriptPatchEdits, capabilities: { type: 'array', maxItems: 6, uniqueItems: true, items: { enum: ['read', 'input', 'debug', 'scene', 'physics', 'asset'] } } }, ['baseRevision', 'expectedDigest', 'edits'], ['entityId', 'scriptId', 'capabilities']), ['studio.script-preview'], 20_000, 64 * 1024, false, ['edits']),
  definition('script.apply', 'Apply script proposal', 'Commit a script proposal through Document History only after script.propose returned zero error diagnostics. If propose reports any error, rewrite the complete function-body script and propose again instead of calling this tool.', 'trusted-code', 'high', schema({ baseRevision: revision, proposalId: { type: 'string', pattern: '^script-proposal:' } }, ['baseRevision', 'proposalId'], []), ['studio.script-preview'], 15_000, 32 * 1024, true),
  definition('preview.validate', 'Validate preview', 'Validate the complete enabled project script set and Scene visual prerequisites, then prepare one trusted Play plan without starting it. By default every enabled script runs in stable order. Supply scriptIds only for an explicit bounded subset; baseRevision is an optional concurrency assertion. Capabilities are inferred independently from each committed script. Lit PBR or blinn-phong geometry is rejected when the Scene has no directional, point, ambient, or environment light, because it would render black.', 'runtime-start', 'high', schema({ baseRevision: revision, scriptIds: { type: 'array', minItems: 1, maxItems: 128, uniqueItems: true, items: scriptId } }, [], ['baseRevision', 'scriptIds']), ['studio.script-preview'], 20_000, 64 * 1024, false),
  definition('preview.start', 'Start preview', 'Start an exact validated trusted preview plan after one-shot authorization.', 'runtime-start', 'high', schema({ baseRevision: revision, planId: { type: 'string', pattern: '^preview-plan:' } }, ['baseRevision', 'planId'], []), ['studio.script-preview', 'studio.preview-control'], 15_000, 32 * 1024, true),
  definition('preview.stop', 'Stop preview', 'Stop and release the currently owned preview runtime.', 'runtime-start', 'medium', empty, ['studio.preview-control'], 10_000, 16 * 1024, false),
  definition('play.start', 'Start Play', 'Start an exact validated trusted Play plan after one-shot authorization. The plan is consumed by a successful start and cannot restart gameplay; use the game\'s restart input, or stop and call preview.validate for a new plan. This is the observation-loop alias of preview.start.', 'runtime-start', 'high', schema({ baseRevision: revision, planId: { type: 'string', pattern: '^preview-plan:' } }, ['baseRevision', 'planId'], []), ['play.multi-script', 'play.inspect'], 15_000, 32 * 1024, true),
  definition('play.stop', 'Stop Play', 'Capture lifecycle cleanup evidence and stop the currently owned Play instance.', 'runtime-start', 'medium', empty, ['play.inspect'], 10_000, 32 * 1024, false),
  definition('play.step', 'Step fixed Play', 'Pause the active Play instance if needed, advance 1-10000 fixed simulation ticks, and persist a state observation before returning its evidence id.', 'observe', 'low', schema({ count: { type: 'integer', minimum: 1, maximum: 10_000 } }, ['count']), ['play.inspect'], 15_000, 64 * 1024),
  definition('play.input', 'Inject Play input', 'Inject one bounded action or pointer event into the active fixed-step Play timeline and persist the resulting state observation.', 'observe', 'low', schema({ event: playInputEvent }, ['event']), ['play.inspect'], 10_000, 64 * 1024),
  definition('play.physics-query', 'Query Play physics', 'Run one bounded status, collision-event, body, raycast or overlap query against the active Play physics authority and persist the result with current tick/frame provenance.', 'observe', 'low', schema({
    kind: { enum: ['status', 'events', 'body', 'raycast', 'overlap'] }, dimension: { enum: ['2d', '3d'] }, entityId,
    origin: vec3, direction: vec3, center: vec3, size: vec3, maxDistance: { type: 'number', exclusiveMinimum: 0, maximum: 1_000_000 }, sinceTick: revision, limit: { type: 'integer', minimum: 1, maximum: 256 },
  }, ['kind'], ['dimension', 'entityId', 'origin', 'direction', 'center', 'size', 'maxDistance', 'sinceTick', 'limit']), ['physics.raycast', 'play.inspect'], 10_000, 64 * 1024),
  definition('play.inspect', 'Inspect Play state', 'Capture and persist a bounded state, input, event, physics, effects and HUD observation from the active Play instance. A preview start acknowledgement is not acceptance evidence.', 'observe', 'low', empty, ['play.inspect'], 10_000, 64 * 1024),
  definition('play.capture', 'Capture Play screenshot', 'Capture the active Play canvas as a bounded PNG, persist the binary in content-addressed storage, and return only provenance metadata and the evidence id.', 'observe', 'low', empty, ['play.capture'], 15_000, 32 * 1024),
  definition('task.evaluate', 'Evaluate task acceptance', 'Evaluate a TaskSpec against persisted, provenance-compatible observations. Assertions use the fixed evidence DSL; unsupported semantic or visual claims are blocked rather than guessed.', 'observe', 'low', schema({ taskSpec, observationIds: { type: 'array', minItems: 1, maxItems: 256, uniqueItems: true, items: { type: 'string', pattern: '^artifact:sha256:' } }, budgetStatus: { enum: ['within', 'soft-exceeded', 'hard-exceeded'] }, usageRecordIds: { type: 'array', maxItems: 256, uniqueItems: true, items: { type: 'string' } }, costRecordIds: { type: 'array', maxItems: 256, uniqueItems: true, items: { type: 'string' } } }, ['taskSpec', 'observationIds'], ['budgetStatus', 'usageRecordIds', 'costRecordIds']), ['task.evaluate'], 15_000, 64 * 1024),
]);

export const GAME_AUTHORING_TOOL_BY_ID: ReadonlyMap<StableId, GameToolDefinition> = new Map(GAME_AUTHORING_TOOL_DEFINITIONS.map((item) => [item.id, item]));

function definition(
  id: string, title: string, description: string, effect: GameToolEffect, risk: GameToolRisk, inputSchema: JsonObject,
  capabilities: readonly string[], timeoutMs = 10_000, maxResultBytes = 32 * 1024, requiresApproval = false, redactedFields: readonly string[] = [],
): GameToolDefinition {
  return Object.freeze({
    schemaVersion: 1, id: asStableId(id), version: '1.0.0', title, description, effect, risk,
    requiredCapabilities: Object.freeze(capabilities.map((item) => asStableId(item))), inputSchema, outputSchema: resultSchema,
    redactedFields: Object.freeze([...redactedFields]), presentation: Object.freeze({ intent: title, result: `${title} result` }),
    timeoutMs, maxResultBytes, requiresApproval, concurrencySafe: PARALLEL_SAFE_TOOL_IDS.has(id),
  });
}

function schema(properties: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): JsonObject {
  const allowed = new Set([...required, ...optional]);
  if (Object.keys(properties).some((key) => !allowed.has(key))) throw new Error('Schema property is not classified as required or optional.');
  return Object.freeze({ type: 'object', additionalProperties: false, required: Object.freeze([...required]), properties: Object.freeze(properties) }) as JsonObject;
}
