import test from 'node:test';
import assert from 'node:assert/strict';
import {Entity,CartesianTransform3D,Camera3D,SphericalTransform3D} from '@haiyue/engine';
import {createPlayTransforms,playWorldMatrix} from '../dist/play-transforms.js';
import {inverse,multiply,transformPoint,rotationAround} from '@haiyue/ai-studio-script-preview/transforms';
function near(a,b){assert.equal(a.length,b.length);a.forEach((v,i)=>assert.ok(Math.abs(v-b[i])<1e-4,`${i}: ${v} vs ${b[i]}`));}
function fixture(){const root=new Entity('root');root.addComponent(new CartesianTransform3D({position:[3,1,-2],rotation:[.2,.4,0]}));const cube=new Entity('cube');cube.addComponent(new CartesianTransform3D({position:[2,0,0]}));root.addChild(cube);const api=createPlayTransforms(id=>{if(id==='cube')return cube;if(id==='root')return root;throw Error('missing')},()=>new Camera3D().projectionMatrix,()=>1);return {root,cube,api};}
test('absolute group rotations preserve parent space and compose cross-axis orientation; cancel and inverse restore',()=>{const {cube,api}=fixture();const initial=playWorldMatrix(cube);const s=api.capture(['cube']);api.rotate(s,[0,0,0],[0,1,0],Math.PI/2);near(playWorldMatrix(cube),multiply(rotationAround([0,0,0],[0,1,0],Math.PI/2),initial));const once=playWorldMatrix(cube);api.rotate(s,[0,0,0],[0,1,0],Math.PI/2);near(playWorldMatrix(cube),once);const s2=api.capture(['cube']);api.rotate(s2,[0,0,0],[1,0,0],Math.PI/2);near(playWorldMatrix(cube),multiply(rotationAround([0,0,0],[1,0,0],Math.PI/2),once));api.rotate(s2,[0,0,0],[1,0,0],0);near(playWorldMatrix(cube),once);api.rotate(api.capture(['cube']),[0,0,0],[0,1,0],-Math.PI/2);near(playWorldMatrix(cube),initial);near(api.localPoint('cube',api.worldPoint('cube',[1,2,3])),[1,2,3]);assert.throws(()=>api.capture(['root','cube']),/descendant/);});
test('four quarter turns restore transforms without Euler accumulation',()=>{const {cube,api}=fixture();const initial=playWorldMatrix(cube);for(let i=0;i<4;i++)api.rotate(api.capture(['cube']),[1,2,3],[0,0,1],Math.PI/2);near(playWorldMatrix(cube),initial);});
test('camera-aware drag sign works in both projections after camera orbit and resize',()=>{for(const type of ['perspective','orthographic'])for(const aspect of [.5,2])for(const theta of [.3,2.4]){const camera=new Entity('camera');camera.addComponent(new SphericalTransform3D({radius:10,phi:1.1,theta}));const projection=new Camera3D({type,aspect,left:-6*aspect,right:6*aspect,top:6,bottom:-6});camera.addComponent(projection);const vp=()=>multiply(projection.projectionMatrix,inverse(playWorldMatrix(camera)));const api=createPlayTransforms(()=>camera,vp,()=>aspect);const point=[0,3,1],pivot=[0,0,0],axis=[0,0,1];const a=api.projectPoint(point),b=api.projectPoint(transformPoint(rotationAround(pivot,axis,.01),point));const delta=[b[0]-a[0],b[1]-a[1]];assert.ok(api.dragAngle(point,pivot,axis,delta)>0);assert.ok(api.dragAngle(point,pivot,axis,delta.map(v=>-v))<0);}});
