import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('packaged desktop sources retain the Electron security and CSP invariants', async () => {
  const main = await readFile(new URL('../dist/main.js', import.meta.url), 'utf8');
  const preload = await readFile(new URL('../dist/preload.cjs', import.meta.url), 'utf8');
  const renderer = await readFile(new URL('../dist/renderer.js', import.meta.url), 'utf8');
  const html = await readFile(new URL('../dist/index.html', import.meta.url), 'utf8');
  const previewHtml = await readFile(new URL('../dist/preview.html', import.meta.url), 'utf8');
  const previewRuntime = await readFile(new URL('../dist/preview-runtime.js', import.meta.url), 'utf8');
  assert.match(main, /contextIsolation:\s*true/);
  assert.match(main, /nodeIntegration:\s*false/);
  assert.match(main, /sandbox:\s*true/);
  assert.match(main, /webSecurity:\s*true/);
  assert.match(main, /devTools:\s*true/);
  assert.match(main, /role:\s*'toggleDevTools'/);
  assert.match(main, /HAIYUE_OPEN_DEVTOOLS/);
  assert.match(main, /setWindowOpenHandler/);
  assert.match(main, /will-navigate/);
  assert.match(main, /persist:haiyue-ai-studio/);
  assert.match(main, /setPath\('userData',[\s\S]*descriptor\.productName/);
  assert.match(preload, /studio:request/);
  assert.match(preload, /studio:cancel/);
  assert.match(preload, /studio:conversation-changed/);
  assert.match(preload, /removeListener\(CONVERSATION_CHANGED_CHANNEL/);
  assert.doesNotMatch(preload, /child_process|node:fs|shell\.openExternal/);
  assert.doesNotMatch(preload, /event\.sender|webContents|conversation\/replay/);
  assert.doesNotMatch(renderer, /node:fs|child_process|ipcRenderer|require\(/);
  assert.doesNotMatch(previewRuntime, /node:fs|child_process|ipcRenderer|require\(/);
  assert.match(html, /Content-Security-Policy/);
  assert.match(html, /href="\.\/styles\.css"/);
  assert.doesNotMatch(html, /<style[\s>]/);
  assert.match(html, /script-src 'self'; style-src 'self' 'unsafe-inline'/);
  assert.doesNotMatch(html, /script-src[^;]*unsafe-inline/);
  assert.match(html, /connect-src 'none'/);
  assert.match(html, /frame-src haiyue-preview:/);
  assert.doesNotMatch(html, /unsafe-eval/);
  assert.match(previewHtml, /script-src 'self' 'unsafe-eval'/);
  assert.match(previewHtml, /connect-src 'none'/);
  assert.match(renderer, /haiyue-preview:\/\/app\/preview\.html/);
  assert.match(renderer, /allow-scripts/);
  assert.doesNotMatch(renderer, /allow-same-origin/);
  assert.match(main, /preview\.html/);
  assert.match(main, /preview-runtime\.js/);
  assert.match(main, /access-control-allow-origin/);
  assert.doesNotMatch(html, /https?:\/\//);
});
