import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
import {OperationLog,createTeamSessionJournal} from '../dist/index.js';
const frame={schemaVersion:1,sessionId:'session:team',header:{version:4,id:'session:team',createdAt:1,isSeeded:false},inheritedEventCount:0,offset:0,events:[{seq:0,type:'fixture',data:{text:'facts'}}]};
async function fixture(t){const directory=await mkdtemp(path.join(tmpdir(),'team-journal-'));let log=await OperationLog.open({rootDirectory:directory,appVersion:'test'});const locks=new Set();const claims={async acquire(id){if(locks.has(id))return null;locks.add(id);return {async release(){locks.delete(id)}}}};const journal=createTeamSessionJournal(log,claims);t.after(async()=>{await log.close();await rm(directory,{recursive:true,force:true})});return {journal,log,claims,async reopen(){await log.close();log=await OperationLog.open({rootDirectory:directory,appVersion:'test'});return createTeamSessionJournal(log,claims)}};}
test('frames replay from disk with exclusive write leases and contiguous immutable prefixes',async t=>{const f=await fixture(t);await assert.rejects(f.journal.append(frame),/unavailable/);const lease=await f.journal.acquire(frame.sessionId);assert.equal(await createTeamSessionJournal(f.log,f.claims).acquire(frame.sessionId),null);
 // A failed append poisons that adapter; use a new adapter after reacquiring the lease.
 await assert.rejects(lease.release());const journal=createTeamSessionJournal(f.log,f.claims);const owner=await journal.acquire(frame.sessionId);await journal.append(frame);await owner.release();const reopened=await f.reopen();assert.deepEqual(await reopened.read(frame.sessionId),[frame]);
 const next=await reopened.acquire(frame.sessionId);await assert.rejects(reopened.append({...frame,offset:0}),/conflict/);await assert.rejects(next.release());});
for(const mode of ['version','secret','reasoning','oversize'])test(`refuse ${mode} before journal writes`,async t=>{const f=await fixture(t);const lease=await f.journal.acquire(frame.sessionId);const value=structuredClone(frame);if(mode==='version')value.schemaVersion=99;if(mode==='secret')value.events[0].data.apiKey='fixture-secret';if(mode==='reasoning')value.events[0].data.content=[{type:'reasoning',text:'private fixture'}];if(mode==='oversize')value.events[0].data.text='x'.repeat(1_048_577);await assert.rejects(f.journal.append(value));assert.deepEqual(await f.journal.read(frame.sessionId),[]);await lease.release();});
test('missing or truncated frames refuse recovery instead of creating a different state',async t=>{const f=await fixture(t);const lease=await f.journal.acquire(frame.sessionId);await f.journal.append(frame);await lease.release();const artifact=await f.log.putArtifact({...frame,offset:9});await f.log.append({kind:'agent/team-session-frame',source:'studio.team-journal',severity:'info',correlation:{sessionId:frame.sessionId},payload:{artifactId:artifact.id,previous:null},artifactRefs:[artifact.id]});await assert.rejects(f.journal.read(frame.sessionId),/chain-invalid/);});
